version: "3"
services:
  volume-setup:
    image: mozsearch-indexer
    build:
      context: ./indexer
      dockerfile: Dockerfile
    user: root
    volumes:
      - index:/index
    entrypoint: ["chown", "builder", "/index"]

  indexer-setup:
    image: mozsearch-indexer
    depends_on:
      - volume-setup
    build:
      context: ./indexer
      dockerfile: Dockerfile
    user: builder
    volumes:
      - "${CONFIGDIR}:/config"
      - "${MOZSEARCHDIR}:/mozsearch"
      - index:/index
    working_dir: /home/builder
    entrypoint: ["bash", "/mozsearch/infrastructure/indexer-setup.sh", "/config", "${CONFIGJSON}", "/index"]

  indexer:
    build:
      context: ./indexer
      dockerfile: Dockerfile
    user: builder
    volumes:
      - "${CONFIGDIR}:/config"
      - "${MOZSEARCHDIR}:/mozsearch"
      - index:/index
    working_dir: /home/builder
    entrypoint: ["bash", "/mozsearch/infrastructure/indexer-run.sh", "/config", "/index"]

  web:
    image: mozsearch-web
    build:
      context: ./web-server
      dockerfile: Dockerfile
    user: root
    ports:
      - "8000:80"
    volumes:
      - "${CONFIGDIR}:/config"
      - "${MOZSEARCHDIR}:/mozsearch"
      - index:/index
    working_dir: /root
    entrypoint: ["bash", "/root/entrypoint.sh", "/config", "${CONFIGJSON}", "/index", "/webroot"]

volumes:
    index:
